package HW1;


import java.security.SecureRandom;

import edu.rit.crypto.blockcipher.AES256Cipher;
import edu.rit.util.Hex;
import java.util.Arrays;

public class EncryptAES256 {
	// Prevent construction.
    private EncryptAES256() {}
    
	public static void main(String[] args) throws Exception {
		 long t1 = System.currentTimeMillis();
		 String message = "Augusta Ada King Noel Countess of Lovelace was an English mathematician and writer chiefly "
		 				+ "known for her work on Charles Babbages proposed mechanical genera purpose computer the Analytical"
		 				+ " Engine She was the first to recognise that the machine had applications beyond pure calculation, and"
		 				+ " created the first algorithm intended to be carried out by such a machine As a result she is often regarded"
		 				+ " as the first to recognise the full potential of a computing machine and the first computer programmer Ada "
		 				+ "Lovelace was the only legitimate child of the poet George Lord Byron and his wife Anne Isabella "
		 				+ "Milbanke Annabella Lady Wentworth All Byrons other children were born out of wedlock to other women"
		 				+ "Byron separated from his wife a month after Ada was born and left England forever four months later eventually"
		 				+ " dying of disease in the Greek War of Independence when Ada was eight years old Her mother remained bitter "
		 				+ "towards Lord Byron and promoted Ada's interest in mathematics and logic in an effort to prevent her from "
		 				+ "developing what she saw as the insanity seen in her father but Ada remained interested in him despite this "
		 				+ "Often ill she spent most of her childhood sick Ada married William King in 1835 King was made Earl of Lovelace "
		 				+ "in 1838 and she became Countess of Lovelace Her educational and social exploits brought her into contact with "
		 				+ "scientists such as Andrew Crosse, Sir David Brewster, Charles Wheatstone, Michael Faraday and the author Charles "
		 				+ "Dickens, which she used to further her education Ada described her approach as poetical science and herself as an Analyst"
		 				+ " When she was a teenager, her mathematical talents led her to a long working relationship and "
		 				+ "friendship with fellow British mathematician Charles Babbage, also known as the father of computers, "
		 				+ "and in particular, Babbages work on the Analytical Engine. Lovelace first met him in June 1833, "
		 				+ "through their mutual friend, and her private tutor, Mary Somerville. Between 1842 and 1843, Ada "
		 				+ "translated an article by Italian military engineer Luigi Menabrea on the engine, which she "
		 				+ "supplemented with an elaborate set of notes, simply called Notes. These notes contain what many "
		 				+ "consider to be the first computer program—that is, an algorithm designed to be carried out by a "
		 				+ "machine. Lovelace's notes are important in the early history of computers. She also developed a "
		 				+ "vision of the capability of computers to go beyond mere calculating or number-crunching, while many "
		 				+ "others, including Babbage himself, focused only on those capabilities. Her mindset of poetical "
		 				+ "science led her to ask questions about the Analytical Engine examining how individuals and society "
		 				+ "relate to technology as a collaborative tool Augusta Ada King Noel Countess of Lovelace was an English mathematician and writer chiefly "
		 				+ "known for her work on Charles Babbages proposed mechanical genera purpose computer the Analytical"
		 				+ " Engine She was the first to recognise that the machine had applications beyond pure calculation, and"
		 				+ " created the first algorithm intended to be carried out by such a machine As a result she is often regarded"
		 				+ " as the first to recognise the full potential of a computing machine and the first computer programmer Ada "
		 				+ "Lovelace was the only legitimate child of the poet George Lord Byron and his wife Anne Isabella "
		 				+ "Milbanke Annabella Lady Wentworth All Byrons other children were born out of wedlock to other women"
		 				+ "Byron separated from his wife a month after Ada was born and left England forever four months later eventually"
		 				+ " dying of disease in the Greek War of Independence when Ada was eight years old Her mother remained bitter "
		 				+ "towards Lord Byron and promoted Ada's interest in mathematics and logic in an effort to prevent her from "
		 				+ "developing what she saw as the insanity seen in her father but Ada remained interested in him despite this "
		 				+ "Often ill she spent most of her childhood sick Ada married William King in 1835 King was made Earl of Lovelace "
		 				+ "in 1838 and she became Countess of Lovelace Her educational and social exploits brought her into contact with "
		 				+ "scientists such as Andrew Crosse, Sir David Brewster, Charles Wheatstone, Michael Faraday and the author Charles "
		 				+ "Dickens, which she used to further her education Ada described her approach as poetical science and herself as an Analyst"
		 				+ " When she was a teenager, her mathematical talents led her to a long working relationship and "
		 				+ "friendship with fellow British mathematician Charles Babbage, also known as the father of computers, "
		 				+ "and in particular, Babbages work on the Analytical Engine. Lovelace first met him in June 1833, "
		 				+ "through their mutual friend, and her private tutor, Mary Somerville. Between 1842 and 1843, Ada "
		 				+ "translated an article by Italian military engineer Luigi Menabrea on the engine, which she "
		 				+ "supplemented with an elaborate set of notes, simply called Notes. These notes contain what many "
		 				+ "consider to be the first computer program—that is, an algorithm designed to be carried out by a "
		 				+ "machine. Lovelace's notes are important in the early history of computers. She also developed a "
		 				+ "vision of the capability of computers to go beyond mere calculating or number-crunching, while many "
		 				+ "others, including Babbage himself, focused only on those capabilities. Her mindset of poetical "
		 				+ "science led her to ask questions about the Analytical Engine examining how individuals and society "
		 				+ "relate to technology as a collaborative tool Augusta Ada King Noel Countess of Lovelace was an English mathematician and writer chiefly "
		 				+ "known for her work on Charles Babbages proposed mechanical genera purpose computer the Analytical"
		 				+ " Engine She was the first to recognise that the machine had applications beyond pure calculation, and"
		 				+ " created the first algorithm intended to be carried out by such a machine As a result she is often regarded"
		 				+ " as the first to recognise the full potential of a computing machine and the first computer programmer Ada "
		 				+ "Lovelace was the only legitimate child of the poet George Lord Byron and his wife Anne Isabella "
		 				+ "Milbanke Annabella Lady Wentworth All Byrons other children were born out of wedlock to other women"
		 				+ "Byron separated from his wife a month after Ada was born and left England forever four months later eventually"
		 				+ " dying of disease in the Greek War of Independence when Ada was eight years old Her mother remained bitter "
		 				+ "towards Lord Byron and promoted Ada's interest in mathematics and logic in an effort to prevent her from "
		 				+ "developing what she saw as the insanity seen in her father but Ada remained interested in him despite this "
		 				+ "Often ill she spent most of her childhood sick Ada married William King in 1835 King was made Earl of Lovelace "
		 				+ "in 1838 and she became Countess of Lovelace Her educational and social exploits brought her into contact with "
		 				+ "scientists such as Andrew Crosse, Sir David Brewster, Charles Wheatstone, Michael Faraday and the author Charles "
		 				+ "Dickens, which she used to further her education Ada described her approach as poetical science and herself as an Analyst"
		 				+ " When she was a teenager, her mathematical talents led her to a long working relationship and "
		 				+ "friendship with fellow British mathematician Charles Babbage, also known as the father of computers, "
		 				+ "and in particular, Babbages work on the Analytical Engine. Lovelace first met him in June 1833, "
		 				+ "through their mutual friend, and her private tutor, Mary Somerville. Between 1842 and 1843, Ada "
		 				+ "translated an article by Italian military engineer Luigi Menabrea on the engine, which she "
		 				+ "supplemented with an elaborate set of notes, simply called Notes. These notes contain what many "
		 				+ "consider to be the first computer program—that is, an algorithm designed to be carried out by a "
		 				+ "machine. Lovelace's notes are important in the early history of computers. She also developed a "
		 				+ "vision of the capability of computers to go beyond mere calculating or number-crunching, while many "
		 				+ "others, including Babbage himself, focused only on those capabilities. Her mindset of poetical "
		 				+ "science led her to ask questions about the Analytical Engine examining how individuals and society "
		 				+ "relate to technology as a collaborative tool Augusta Ada King Noel Countess of Lovelace was an English mathematician and writer chiefly "
		 				+ "known for her work on Charles Babbages proposed mechanical genera purpose computer the Analytical"
		 				+ " Engine She was the first to recognise that the machine had applications beyond pure calculation, and"
		 				+ " created the first algorithm intended to be carried out by such a machine As a result she is often regarded"
		 				+ " as the first to recognise the full potential of a computing machine and the first computer programmer Ada "
		 				+ "Lovelace was the only legitimate child of the poet George Lord Byron and his wife Anne Isabella "
		 				+ "Milbanke Annabella Lady Wentworth All Byrons other children were born out of wedlock to other women"
		 				+ "Byron separated from his wife a month after Ada was born and left England forever four months later eventually"
		 				+ " dying of disease in the Greek War of Independence when Ada was eight years old Her mother remained bitter "
		 				+ "towards Lord Byron and promoted Ada's interest in mathematics and logic in an effort to prevent her from "
		 				+ "developing what she saw as the insanity seen in her father but Ada remained interested in him despite this "
		 				+ "Often ill she spent most of her childhood sick Ada married William King in 1835 King was made Earl of Lovelace "
		 				+ "in 1838 and she became Countess of Lovelace Her educational and social exploits brought her into contact with "
		 				+ "scientists such as Andrew Crosse, Sir David Brewster, Charles Wheatstone, Michael Faraday and the author Charles "
		 				+ "Dickens, which she used to further her education Ada described her approach as poetical science and herself as an Analyst"
		 				+ " When she was a teenager, her mathematical talents led her to a long working relationship and "
		 				+ "friendship with fellow British mathematician Charles Babbage, also known as the father of computers, "
		 				+ "and in particular, Babbages work on the Analytical Engine. Lovelace first met him in June 1833, "
		 				+ "through their mutual friend, and her private tutor, Mary Somerville. Between 1842 and 1843, Ada "
		 				+ "translated an article by Italian military engineer Luigi Menabrea on the engine, which she "
		 				+ "supplemented with an elaborate set of notes, simply called Notes. These notes contain what many "
		 				+ "consider to be the first computer program—that is, an algorithm designed to be carried out by a "
		 				+ "machine. Lovelace's notes are important in the early history of computers. She also developed a "
		 				+ "vision of the capability of computers to go beyond mere calculating or number-crunching, while many "
		 				+ "others, including Babbage himself, focused only on those capabilities. Her mindset of poetical "
		 				+ "science led her to ask questions about the Analytical Engine examining how individuals and society "
		 				+ "relate to technology as a collaborative tool Augusta Ada King Noel Countess of Lovelace was an English mathematician and writer chiefly "
		 				+ "known for her work on Charles Babbages proposed mechanical genera purpose computer the Analytical"
		 				+ " Engine She was the first to recognise that the machine had applications beyond pure calculation, and"
		 				+ " created the first algorithm intended to be carried out by such a machine As a result she is often regarded"
		 				+ " as the first to recognise the full potential of a computing machine and the first computer programmer Ada "
		 				+ "Lovelace was the only legitimate child of the poet George Lord Byron and his wife Anne Isabella "
		 				+ "Milbanke Annabella Lady Wentworth All Byrons other children were born out of wedlock to other women"
		 				+ "Byron separated from his wife a month after Ada was born and left England forever four months later eventually"
		 				+ " dying of disease in the Greek War of Independence when Ada was eight years old Her mother remained bitter "
		 				+ "towards Lord Byron and promoted Ada's interest in mathematics and logic in an effort to prevent her from "
		 				+ "developing what she saw as the insanity seen in her father but Ada remained interested in him despite this "
		 				+ "Often ill she spent most of her childhood sick Ada married William King in 1835 King was made Earl of Lovelace "
		 				+ "in 1838 and she became Countess of Lovelace Her educational and social exploits brought her into contact with "
		 				+ "scientists such as Andrew Crosse, Sir David Brewster, Charles Wheatstone, Michael Faraday and the author Charles "
		 				+ "Dickens, which she used to further her education Ada described her approach as poetical science and herself as an Analyst"
		 				+ " When she was a teenager, her mathematical talents led her to a long working relationship and "
		 				+ "friendship with fellow British mathematician Charles Babbage, also known as the father of computers, "
		 				+ "and in particular, Babbages work on the Analytical Engine. Lovelace first met him in June 1833, "
		 				+ "through their mutual friend, and her private tutor, Mary Somerville. Between 1842 and 1843, Ada "
		 				+ "translated an article by Italian military engineer Luigi Menabrea on the engine, which she "
		 				+ "supplemented with an elaborate set of notes, simply called Notes. These notes contain what many "
		 				+ "consider to be the first computer program—that is, an algorithm designed to be carried out by a "
		 				+ "machine. Lovelace's notes are important in the early history of computers. She also developed a "
		 				+ "vision of the capability of computers to go beyond mere calculating or number-crunching, while many "
		 				+ "others, including Babbage himself, focused only on those capabilities. Her mindset of poetical "
		 				+ "science led her to ask questions about the Analytical Engine examining how individuals and society "
		 				+ "relate to technology as a collaborative tool Augusta Ada King Noel Countess of Lovelace was an English mathematician and writer chiefly "
		 				+ "known for her work on Charles Babbages proposed mechanical genera purpose computer the Analytical"
		 				+ " Engine She was the first to recognise that the machine had applications beyond pure calculation, and"
		 				+ " created the first algorithm intended to be carried out by such a machine As a result she is often regarded"
		 				+ " as the first to recognise the full potential of a computing machine and the first computer programmer Ada "
		 				+ "Lovelace was the only legitimate child of the poet George Lord Byron and his wife Anne Isabella "
		 				+ "Milbanke Annabella Lady Wentworth All Byrons other children were born out of wedlock to other women"
		 				+ "Byron separated from his wife a month after Ada was born and left England forever four months later eventually"
		 				+ " dying of disease in the Greek War of Independence when Ada was eight years old Her mother remained bitter "
		 				+ "towards Lord Byron and promoted Ada's interest in mathematics and logic in an effort to prevent her from "
		 				+ "developing what she saw as the insanity seen in her father but Ada remained interested in him despite this "
		 				+ "Often ill she spent most of her childhood sick Ada married William King in 1835 King was made Earl of Lovelace "
		 				+ "in 1838 and she became Countess of Lovelace Her educational and social exploits brought her into contact with "
		 				+ "scientists such as Andrew Crosse, Sir David Brewster, Charles Wheatstone, Michael Faraday and the author Charles "
		 				+ "Dickens, which she used to further her education Ada described her approach as poetical science and herself as an Analyst"
		 				+ " When she was a teenager, her mathematical talents led her to a long working relationship and "
		 				+ "friendship with fellow British mathematician Charles Babbage, also known as the father of computers, "
		 				+ "and in particular, Babbages work on the Analytical Engine. Lovelace first met him in June 1833, "
		 				+ "through their mutual friend, and her private tutor, Mary Somerville. Between 1842 and 1843, Ada "
		 				+ "translated an article by Italian military engineer Luigi Menabrea on the engine, which she "
		 				+ "supplemented with an elaborate set of notes, simply called Notes. These notes contain what many "
		 				+ "consider to be the first computer program—that is, an algorithm designed to be carried out by a "
		 				+ "machine. Lovelace's notes are important in the early history of computers. She also developed a "
		 				+ "vision of the capability of computers to go beyond mere calculating or number-crunching, while many "
		 				+ "others, including Babbage himself, focused only on those capabilities. Her mindset of poetical "
		 				+ "science led her to ask questions about the Analytical Engine examining how individuals and society "
		 				+ "relate to technology as a collaborative tool Augusta Ada King Noel Countess of Lovelace was an English mathematician and writer chiefly "
		 				+ "known for her work on Charles Babbages proposed mechanical genera purpose computer the Analytical"
		 				+ " Engine She was the first to recognise that the machine had applications beyond pure calculation, and"
		 				+ " created the first algorithm intended to be carried out by such a machine As a result she is often regarded"
		 				+ " as the first to recognise the full potential of a computing machine and the first computer programmer Ada "
		 				+ "Lovelace was the only legitimate child of the poet George Lord Byron and his wife Anne Isabella "
		 				+ "Milbanke Annabella Lady Wentworth All Byrons other children were born out of wedlock to other women"
		 				+ "Byron separated from his wife a month after Ada was born and left England forever four months later eventually"
		 				+ " dying of disease in the Greek War of Independence when Ada was eight years old Her mother remained bitter "
		 				+ "towards Lord Byron and promoted Ada's interest in mathematics and logic in an effort to prevent her from "
		 				+ "developing what she saw as the insanity seen in her father but Ada remained interested in him despite this "
		 				+ "Often ill she spent most of her childhood sick Ada married William King in 1835 King was made Earl of Lovelace "
		 				+ "in 1838 and she became Countess of Lovelace Her educational and social exploits brought her into contact with "
		 				+ "scientists such as Andrew Crosse, Sir David Brewster, Charles Wheatstone, Michael Faraday and the author Charles "
		 				+ "Dickens, which she used to further her education Ada described her approach as poetical science and herself as an Analyst"
		 				+ " When she was a teenager, her mathematical talents led her to a long working relationship and "
		 				+ "friendship with fellow British mathematician Charles Babbage, also known as the father of computers, "
		 				+ "and in particular, Babbages work on the Analytical Engine. Lovelace first met him in June 1833, "
		 				+ "through their mutual friend, and her private tutor, Mary Somerville. Between 1842 and 1843, Ada "
		 				+ "translated an article by Italian military engineer Luigi Menabrea on the engine, which she "
		 				+ "supplemented with an elaborate set of notes, simply called Notes. These notes contain what many "
		 				+ "consider to be the first computer program—that is, an algorithm designed to be carried out by a "
		 				+ "machine. Lovelace's notes are important in the early history of computers. She also developed a "
		 				+ "vision of the capability of computers to go beyond mere calculating or number-crunching, while many "
		 				+ "others, including Babbage himself, focused only on those capabilities. Her mindset of poetical "
		 				+ "science led her to ask questions about the Analytical Engine examining how individuals and society "
		 				+ "relate to technology as a collaborative tool Augusta Ada King Noel Countess of Lovelace was an English mathematician and writer chiefly "
		 				+ "known for her work on Charles Babbages proposed mechanical genera purpose computer the Analytical"
		 				+ " Engine She was the first to recognise that the machine had applications beyond pure calculation, and"
		 				+ " created the first algorithm intended to be carried out by such a machine As a result she is often regarded"
		 				+ " as the first to recognise the full potential of a computing machine and the first computer programmer Ada "
		 				+ "Lovelace was the only legitimate child of the poet George Lord Byron and his wife Anne Isabella "
		 				+ "Milbanke Annabella Lady Wentworth All Byrons other children were born out of wedlock to other women"
		 				+ "Byron separated from his wife a month after Ada was born and left England forever four months later eventually"
		 				+ " dying of disease in the Greek War of Independence when Ada was eight years old Her mother remained bitter "
		 				+ "towards Lord Byron and promoted Ada's interest in mathematics and logic in an effort to prevent her from "
		 				+ "developing what she saw as the insanity seen in her father but Ada remained interested in him despite this "
		 				+ "Often ill she spent most of her childhood sick Ada married William King in 1835 King was made Earl of Lovelace "
		 				+ "in 1838 and she became Countess of Lovelace Her educational and social exploits brought her into contact with "
		 				+ "scientists such as Andrew Crosse, Sir David Brewster, Charles Wheatstone, Michael Faraday and the author Charles "
		 				+ "Dickens, which she used to further her education Ada described her approach as poetical science and herself as an Analyst"
		 				+ " When she was a teenager, her mathematical talents led her to a long working relationship and "
		 				+ "friendship with fellow British mathematician Charles Babbage, also known as the father of computers, "
		 				+ "and in particular, Babbages work on the Analytical Engine. Lovelace first met him in June 1833, "
		 				+ "through their mutual friend, and her private tutor, Mary Somerville. Between 1842 and 1843, Ada "
		 				+ "translated an article by Italian military engineer Luigi Menabrea on the engine, which she "
		 				+ "supplemented with an elaborate set of notes, simply called Notes. These notes contain what many "
		 				+ "consider to be the first computer program—that is, an algorithm designed to be carried out by a "
		 				+ "machine. Lovelace's notes are important in the early history of computers. She also developed a "
		 				+ "vision of the capability of computers to go beyond mere calculating or number-crunching, while many "
		 				+ "others, including Babbage himself, focused only on those capabilities. Her mindset of poetical "
		 				+ "science led her to ask questions about the Analytical Engine examining how individuals and society "
		 				+ "relate to technology as a collaborative tool Augusta Ada King Noel Countess of Lovelace was an English mathematician and writer chiefly "
		 				+ "known for her work on Charles Babbages proposed mechanical genera purpose computer the Analytical"
		 				+ " Engine She was the first to recognise that the machine had applications beyond pure calculation, and"
		 				+ " created the first algorithm intended to be carried out by such a machine As a result she is often regarded"
		 				+ " as the first to recognise the full potential of a computing machine and the first computer programmer Ada "
		 				+ "Lovelace was the only legitimate child of the poet George Lord Byron and his wife Anne Isabella "
		 				+ "Milbanke Annabella Lady Wentworth All Byrons other children were born out of wedlock to other women"
		 				+ "Byron separated from his wife a month after Ada was born and left England forever four months later eventually"
		 				+ " dying of disease in the Greek War of Independence when Ada was eight years old Her mother remained bitter "
		 				+ "towards Lord Byron and promoted Ada's interest in mathematics and logic in an effort to prevent her from "
		 				+ "developing what she saw as the insanity seen in her father but Ada remained interested in him despite this "
		 				+ "Often ill she spent most of her childhood sick Ada married William King in 1835 King was made Earl of Lovelace "
		 				+ "in 1838 and she became Countess of Lovelace Her educational and social exploits brought her into contact with "
		 				+ "scientists such as Andrew Crosse, Sir David Brewster, Charles Wheatstone, Michael Faraday and the author Charles "
		 				+ "Dickens, which she used to further her education Ada described her approach as poetical science and herself as an Analyst"
		 				+ " When she was a teenager, her mathematical talents led her to a long working relationship and "
		 				+ "friendship with fellow British mathematician Charles Babbage, also known as the father of computers, "
		 				+ "and in particular, Babbages work on the Analytical Engine. Lovelace first met him in June 1833, "
		 				+ "through their mutual friend, and her private tutor, Mary Somerville. Between 1842 and 1843, Ada "
		 				+ "translated an article by Italian military engineer Luigi Menabrea on the engine, which she "
		 				+ "supplemented with an elaborate set of notes, simply called Notes. These notes contain what many "
		 				+ "consider to be the first computer program—that is, an algorithm designed to be carried out by a "
		 				+ "machine. Lovelace's notes are important in the early history of computers. She also developed a "
		 				+ "vision of the capability of computers to go beyond mere calculating or number-crunching, while many "
		 				+ "others, including Babbage himself, focused only on those capabilities. Her mindset of poetical "
		 				+ "science led her to ask questions about the Analytical Engine examining how individuals and society "
		 				+ "relate to technology as a collaborat";

		 String keyStr = Hex.toString(SecureRandom.getSeed(32));
         
         byte[] key = Hex.toByteArray(keyStr);
         String encryptedMessage = "";
         byte[] messageBytes = message.getBytes();
         AES256Cipher cipher = new AES256Cipher(key);
         byte[] messageByteBlock = new byte[16];
         
         //16 bitlik bloklara bolmek gerekiyor
         //Each plaintext blocks has 128 bits.
         for (int counter = 0; counter < (messageBytes.length/16); ++counter) {
        	 //key lenght 256 bits
        	 messageByteBlock = Arrays.copyOfRange(messageBytes, counter*16, ((counter+1)*16));
	         cipher.encrypt(messageByteBlock);
	         encryptedMessage += Hex.toString(messageByteBlock);  
         }
         System.out.println("encrypted message:       "+ encryptedMessage);
         System.out.println("message length: "+messageBytes.length+" bytes");
         System.out.println("randomly generated secure key: " + keyStr);
         long t2 = System.currentTimeMillis();
         System.out.println((t2 - t1) + " msec");
	}
}